# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: An AUTOBIOGRAPHY Based On Life Based On Joshua 1:9 ... Discipline Equals Freedom.
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
