# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: I cannot possibly ever communicate how GRATEFUL I am to my Creator for every moment of my existence!
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
