# Site settings
title: AUCT.us
email: MarkBruns@MarkBruns.com
description: To INCREASE is to accelerate the negotiation process.
twitter_username: MarkBruns
github_username:  AuctU

# Build settings
markdown: kramdown
