# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: I cannot possibly ever communicate how GRATEFUL I am to my Creator for every moment of my existence! It is out of this gratitude and love, that I must fall on my knees and earnestly pray that the will of our Creator be done.
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
