# Site settings
title: AUCT.us
email: MarkBruns@MarkBruns.com
description: To INCREASE ... Auct.US is AGENTIC multi-agent AI ... a tool for looking at several sources of information in a market or auction, asset price, trading exchanges, or [accelerated] negotiations. 
twitter_username: MarkBruns
github_username:  AuctU

# Build settings
markdown: kramdown
