# Site settings
title: MarkBruns Tech Blog
email: MarkBruns@MarkBruns.com
description: This is my blog about version-controlled social production of open source technology ... feel free to reach out to me and tell me how I can be of service to you!
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
