# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: You've been COMMANDED to be courageous, to drive forward without hesitation. What part of your mission in Joshua 1.9 did you not understand? SERVE the MISSION 1st!
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
