# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: Discipline Equals Freedom. Freedom is not FREE. It requires the discipline of improving the discipline, to improve the discipline, to improve the discipline to BECOME free. Know your UNIQUE WHY! Joshua 1:9
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
