# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: I cannot possibly ever communicate how GRATEFUL I am to my Creator for every moment of my existence! I try to notice, analyze and articulate my gratitude as well as my appreciation of the work of others each day. Philippians 4:8-9
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
