# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: In the grand scheme of all things, EVERY last thing that the entire population of your species throughout all ages can begin to reach or even contemplate has been absolutely TRIVIAL for our Creator. This is why we must fall on our knees and earnestly pray that the will of our Creator be done.
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
