# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: An imperfect child of God 🌟 attempting to become an empath🧎🏾 who cannot possibly ever communicate how GRATEFUL he is to his Creator for every moment of his existence! Philippians 4:8-9
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
