# Site settings
title: MarkBruns Tech Blag
email: MarkBruns@MarkBruns.com
description: This is my blog about version-controlled social production of open source technology ... and the interconnections to interconnections ... https://xkcd.com/1579/
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
