# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: Every so often I realize that I am a collection of bad habits that I work very hard to maintain; I'm trying to knock that off ... https://xkcd.com/1579/
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
