# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: A convoluted collection of bad habits which I indulge even if they will kill me ... https://xkcd.com/1579/
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
