# Site settings
title: AUCT.us
email: MarkBruns@MarkBruns.com
description: To INCREASE ... accelerate the negotiation.
twitter_username: MarkBruns
github_username:  AuctU

# Build settings
markdown: kramdown
