# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: You will persist as the most backward ignoramus in dumbfuckistan as long as you choose to think that you are the opposite of that. 
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
