# Site settings
title: MarkBruns Tech Blawg
email: MarkBruns@MarkBruns.com
description: This is my blog about version-controlled social production of open source technologies, cultures and revolutions ... and my interconnections to larger, more awesome interconnections in the universe ... https://xkcd.com/1579/
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
