# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: An AUTOBIOGRAPHY On A Life Based On Joshua 1:9. The mission of life is in PERFECTING our lives. Discipline Equals Freedom.
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
