# Site settings
title: AUCT.us
email: MarkBruns@MarkBruns.com
description: An open source resource recovery application framework with AI for the efficient, expeditious IMPROVEMENT of net value of underused, obsolete, decrepit, damaged, discarded or no-longer wanted items.
twitter_username: MarkBruns
github_username:  AuctU

# Build settings
markdown: kramdown
