# Site settings
title: AUCT.us
email: MarkBruns@MarkBruns.com
description: An open source resource recovery application framework with AI for the efficient, expeditious IMPROVEMENT of net value of used or discarded items.
twitter_username: MarkBruns
github_username:  AUCT-us

# Build settings
markdown: kramdown
